apiVersion: batch/v1
kind: Job
metadata:
  name: node-cpu-benchmark
spec:
  parallelism: 3
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: node-cpu-benchmark
    spec:

      containers:
      - name: node-cpu-benchmark
        image: rdelaros/node-cpu-benchmark:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "1"
          limits:
            memory: "128Mi"
            cpu: "1"
      restartPolicy: Never
  backoffLimit: 4

